test(cicd): add some comments re checksum fail

diff --git a/.github/workflows/terraform-plan-and-apply-aws.yml b/.github/workflows/terraform-plan-and-apply-aws.yml
--- a/.github/workflows/terraform-plan-and-apply-aws.yml
+++ b/.github/workflows/terraform-plan-and-apply-aws.yml
@@ -763,11 +763,19 @@ jobs:
       - name: Validate Plan Checksum
         run: |
           if [ ! -f tfplan.checksum ]; then
-            echo "Checksum file missing. Halting apply phase."
+            echo "Checksum file is missing. The tfplan artifact may not have been generated or uploaded correctly. Halting Terraform Apply phase."
             exit 1
           fi
-          echo "Validating checksum..."
-          sha256sum -c tfplan.checksum || { echo "Checksum mismatch. Halting Terraform Apply phase."; exit 1; }
+      
+          echo "Validating the checksum of the tfplan artifact..."
+          if sha256sum -c tfplan.checksum; then
+            echo "Checksum validation succeeded. The tfplan artifact is intact and matches the original plan."
+          else
+            echo "Checksum validation failed. The tfplan artifact has been modified or tampered with since the plan was generated."
+            echo "Halting Terraform Apply phase to ensure the integrity of the deployment process."
+            exit 1
+          fi
+        
       - name: Terraform Apply
         run: |
           # terraform apply \
