fix: commit message

diff --git a/.github/workflows/terraform-module-validation.yml b/.github/workflows/terraform-module-validation.yml
--- a/.github/workflows/terraform-module-validation.yml
+++ b/.github/workflows/terraform-module-validation.yml
@@ -98,6 +98,14 @@ on:
         required: false
         type: string
 
+      trivy-sha256:
+        description: 'Trivy sha256 checksum to verify'
+        required: false
+        type: string
+        default: |
+          d860265c7ebd8128c349d063c91e8f32b26b730d14c2ce85e187fef8be70d72d
+          8266084a71d2e6a2333bc2c69b91c93c26dee9ef39ac2587ace2df54cc9b746b
+
       working-directory:
         default: "."
         description: "Working directory"
@@ -302,6 +310,22 @@ jobs:
           terraform-init-extra-args: ${{ inputs.terraform-init-extra-args }}
           terraform-version: ${{ inputs.terraform-version }}
           working-directory: ${{ inputs.working-directory }}
+      - name: Setup Trivy
+        uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514 # v0.2.6 - see dependabot.yml ignore rule
+        with:
+          version: ${{ inputs.trivy-version }}
+      - name: Verify Trivy Checksum # step added to verify trivy v0.69.3 binary
+        shell: bash
+        run: |
+            EXPECTED_SHA_COLLECTION="${{ inputs.trivy-sha256 }}"
+            ACTUAL_SHA="$(sha256sum $(which trivy) | awk '{print $1}')"
+            echo "Trivy SHA: $ACTUAL_SHA"
+            if echo "$EXPECTED_SHA_COLLECTION" | grep -Fq "$ACTUAL_SHA"; then
+              echo "Trivy binary checksum verified successfully."
+            else
+              echo "Error: Trivy binary checksum mismatch!"
+              exit 1
+            fi
       - name: Run Trivy vulnerability
         id: security
         uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
